spring.application.name=the-green-corner

spring.datasource.url=jdbc:postgresql://localhost:5432/the_green_corner_
spring.datasource.username=postgres
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



################
# properties required for spring-boot-starter-mail dependency which we need to implement
# email service for contactUs functionality:
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#this is our admin email that is green corner's webapp's email. Replace my provided email(it was used
# for testing purpose) with green corner's official email
spring.mail.username=shreyavc7@gmail.com
spring.mail.password=fziduekhtxxfusgf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#admin mail property this is used to inject in service of contactUs to save contactUs object
#  in database and send their complaint/message to admin that it is at this email.
#I have used it in auto reply to client to assure them that we have received their complaint/message
# and also admin can also reply manually through email to their complaint/message as soon as admin
# receives client's mail and can click to reply in gmail itself.
#Replace my provided email(it was used for testing purpose) with green corner's official email
#value in both of these=>spring.mail.username AND app.admin.email must be same as this is
# admin's(greenCorner's) email
app.admin.mail=shreyavc7@gmail.com

#property which is enabling mail services to load welcome image in client's mail after successful
# signup that is account creation. So this property is storing welcome image url. I have hosted this image at
# cloudinary from my cloudinary account
app.email.SignUpWelcomeImg.url=https://res.cloudinary.com/dmyfhwdym/image/upload/v1763293838/SignUpEmailImg_TheGreenCorner_sw1gts.png

